# Generated by Django 4.2.6 on 2023-10-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
